"""Prompt templates for the LLM-based swarm."""

from app.llm.prompts.pedagogical import PEDAGOGICAL_SYSTEM_PROMPT, PEDAGOGICAL_VOTE_PROMPT
from app.llm.prompts.adaptive import ADAPTIVE_SYSTEM_PROMPT, ADAPTIVE_VOTE_PROMPT
from app.llm.prompts.evaluation import EVALUATION_SYSTEM_PROMPT, EVALUATION_VOTE_PROMPT
from app.llm.prompts.deliberation import (
    DELIBERATION_SYSTEM_PROMPT,
    DELIBERATION_VOTE_PROMPT,
    MEDIATION_SYSTEM_PROMPT,
    MEDIATION_PROMPT,
)

__all__ = [
    "PEDAGOGICAL_SYSTEM_PROMPT",
    "PEDAGOGICAL_VOTE_PROMPT",
    "ADAPTIVE_SYSTEM_PROMPT",
    "ADAPTIVE_VOTE_PROMPT",
    "EVALUATION_SYSTEM_PROMPT",
    "EVALUATION_VOTE_PROMPT",
    "DELIBERATION_SYSTEM_PROMPT",
    "DELIBERATION_VOTE_PROMPT",
    "MEDIATION_SYSTEM_PROMPT",
    "MEDIATION_PROMPT",
]
