"""Schema for enriched concept blocks generated by the pedagogical pipeline.

Sprint L1: ConceptBlock bundles a concept with its contextual enrichment
(analogy, curiosity, media_prompt, mini_activity, reflection, knowledge_check)
so the frontend can render a complete micro-learning experience per concept
without any domain-specific logic embedded in the React layer.
"""

from __future__ import annotations

from typing import Literal, Optional

from pydantic import BaseModel


class ConceptBlockAnalogy(BaseModel):
    source:      str
    explanation: str
    image_hint:  Optional[str] = None


class ConceptBlockCuriosity(BaseModel):
    fact:   str
    stat:   Optional[str] = None
    source: Optional[str] = None


class ConceptBlockMediaPrompt(BaseModel):
    type:             Literal['image', 'video', 'audio']
    title:            str
    prompt:           str
    learning_goal:    str
    duration_seconds: Optional[int] = None


class ConceptBlockMiniActivity(BaseModel):
    instructions: str
    steps:        list[str]


class ConceptBlockReflection(BaseModel):
    misconception: str
    correction:    str
    severity:      str = "medium"


class ConceptBlockKnowledgeCheck(BaseModel):
    question:      str
    options:       list[str]
    correct_index: int
    explanation:   str


class ConceptBlock(BaseModel):
    """A self-contained learning unit: concept + all enrichment layers.

    Phase 1 fields (always generated): id, title, explanation, example,
    analogy, curiosity, media_prompt, mini_activity.

    Phase 2 fields (None in Phase 1): reflection, knowledge_check.
    """
    id:                  str
    title:               str
    explanation:         str
    learning_objective:  Optional[str] = None
    example:             Optional[str] = None
    analogy:             Optional[ConceptBlockAnalogy]     = None
    curiosity:           Optional[ConceptBlockCuriosity]   = None
    media_prompt:        Optional[ConceptBlockMediaPrompt] = None
    mini_activity:       Optional[ConceptBlockMiniActivity]    = None
    reflection:          Optional[ConceptBlockReflection]  = None
    knowledge_check:     Optional[ConceptBlockKnowledgeCheck]  = None
